# Access to the data in this file is provided through the EnvConfig class - see env_config.rb

defaults: &execution_defaults
  default_config: ci #This just ensures the ci profile (below) is loaded if no CONFIG= is passed from the command line.

  member_login_path: login/

ci:
  <<: *execution_defaults
  # URLs
  base_url: http://unix.spartaglobal.com/moodle/
  login_url: http://unix.spartaglobal.com/moodle/login/
  course_request_url: http://unix.spartaglobal.com/moodle/course/request.php
  course_page_url: http://unix.spartaglobal.com/moodle/course/index.php
  course_pending_url: http://unix.spartaglobal.com/moodle/course/pending.php
  course_search_url: http://unix.spartaglobal.com/moodle/course/search.php
  course_manage_url: http://unix.spartaglobal.com/moodle/course/management.php?categoryid=1
  logout_url: http://unix.spartaglobal.com/moodle/login/logout.php
  signup_url: http://unix.spartaglobal.com/moodle/login/signup.php?
  third_party_email_url: https://www.guerrillamail.com/inbox
  modify_users_url: http://unix.spartaglobal.com/moodle/admin/user/user_bulk.php
  new_event_url: http://unix.spartaglobal.com/moodle/calendar/event.php?action=new
  calendar_url: http://unix.spartaglobal.com/moodle/calendar/view.php?view=month

  # admin credentials
  admin_username: moodle
  admin_password: soXy3zX2JTRwZCXw!

# Database is currently not used, these are the details if ever needed
  # database_url: 88.208.245.234
  # database_username: moodle
  # database_password: moodle
  # database_name: moodle

uat:
  <<: *execution_defaults
