# Access to the data in this file is provided through the EnvConfig class - see env_config.rb

defaults: &execution_defaults
  default_config: ci #This just ensures the ci profile (below) is loaded if no CONFIG= is passed from the command line.

  member_login_path: login/
  base_url: http://unix.spartaglobal.com/moodle
ci:
  <<: *execution_defaults
  # URLs
  login_url: /login/
  course_approved_url: /course/edit.php?id=
  course_request_url: /course/request.php
  course_page_url: /course/index.php
  course_pending_url: /course/pending.php
  course_search_url: /course/search.php?search=
  course_manage_url: /course/management.php?categoryid=1
  logout_url: /login/logout.php
  signup_url: /login/signup.php
  third_party_email_url: https://www.guerrillamail.com/inbox
  modify_users_url: /admin/user/user_bulk.php
  new_event_url: /calendar/event.php?action=new
  calendar_url: /calendar/view.php?view=month
  my_course_url: /my
  create_group_url: /group/group.php?courseid=
  new_group_event_url: '/calendar/event.php?action=new&course='
  course_enrol: /enrol/users.php?id=
  # admin credentials
  admin_username: moodle
  admin_password: soXy3zX2JTRwZCXw!

# Database is currently not used, these are the details if ever needed
  # database_url: 88.208.245.234
  # database_username: moodle
  # database_password: moodle
  # database_name: moodle

uat:
  <<: *execution_defaults
